config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'blogs' => 'blog#index', as: 'blogs'
  get 'blogs/new' => 'blog#new', as: 'new_blog'
  get 'blog/:id' => 'blog#show', as:'blog'
  post 'blogs' => 'blog#create'
  get 'blog/:id/edit' => 'blog#edit', as: 'edit_blog'
  patch 'blog/:id' => 'blog#update'
  delete 'blog/:id' => 'blog#destroy', as: 'delete_blog'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
    def index
        @blogs= Blog.all
    end

    def show 
        @blog= Blog.find(params[:id])
    end

    def new
        @blog= Blog.new()
    end
    def create
        @blog= Blog.create(blog_params)
        if @blog.valid?
            redirect_to blogs_path
        end
    end
      
    def edit
        @blog = Blog.find(params[:id])
    end
    def update
        @blog = Blog.find(params[:id])
        @blog.update(blog_params)
        if @blog.valid?
        redirect_to blog_path(@blog) 
        end
    end

    def destroy
        @blog = Blog.find(params[:id])
        if @blog.destroy
            redirect_to blogs_path
        end
    end

      private
    def blog_params
        params.require(:blog).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/edit.html.erb
<h1>Edit the Post</h1>
<br/>
<%= form_with model:  @blog, method: :patch do |blog| %>
    <%= blog.label :title %>
    <%= blog.text_field :title %>
    <br />
    <%= blog.label :content %>
    <%= blog.text_field :content %>
    <br />
    <%= blog.submit "Edit Post" %>
  <% end %>
<br />
<p><%= link_to 'Back to Main Page', blogs_path %></p>

app/views/blog/index.html.erb
<h1>Welcome</h1>
<br/>
<h3>Posts</h3>
<ul>
<% @blogs.each do |blog|%>
    <li> <%= link_to blog.title, blog_path(blog) %></li>
   
    <% end %>
</ul>
<%= link_to 'Create a new blog', new_blog_path %>

app/views/blog/new.html.erb
<>Add a Post</>
<br/>
<%= form_with model: @blog do |blog| %>
    <%= blog.label :title %>
    <%= blog.text_field :title %>
    <br />
    <%= blog.label :content %>
    <%= blog.text_field :content %>
    <br />
    <%= blog.submit "Add Post" %>
  <% end %>
<br />
<p><%= link_to 'Back to Main Page', blogs_path %></p>

app/views/blog/show.html.erb
<h1>One Post</h1>
<br/>
<h3><%=@blog.title %></h3>
<p><%=@blog.content%></p>
<br/>
<%= button_to 'delete this shizz', delete_blog_path(@blog), :method=> :delete%>
<%= link_to 'Edit this blog', edit_blog_path(@blog) %>
<p><%= link_to 'Back to Main Page', blogs_path %></p>
<%= link_to 'Create a new blog', new_blog_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogJacobMichael</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>